http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000
spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  gson:
    field-naming-policy: lower_case_with_underscores